# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90560f961873f4bc7d8e1fc12e1b4b8f1806dd82991855d8d5e188558bed1e1acbb49d0a7e9d3699db484088f751a866a70328f786d5855ce90a47ecb49b4d89

test:
  secret_key_base: e779057f826a2c4ffa173a502f533d041a1664bde0c0e8ae1973677c83981529b0c8bc06f705f98f01f9f89824ab3d647523f4c644b824c99c467e44d74c703c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
